INSERT INTO Company (ADDRESS, NAME) VALUES ('pl. na Groblach 55, 01-111 Kraków', 'IT-soft')
INSERT INTO Company (ADDRESS, NAME) VALUES ('ul. Lotnikow 35, 00-001 Kraków', 'I-Finance')

INSERT INTO Employee (FIRSTNAME, LASTNAME, COMPANY) VALUES ('George', 'Cranch', (SELECT ID FROM Company WHERE NAME = 'IT-soft'))
INSERT INTO Employee (FIRSTNAME, LASTNAME, COMPANY) VALUES ('Brad', 'Hummy', (SELECT ID FROM Company WHERE NAME = 'I-Finance'))
INSERT INTO Employee (FIRSTNAME, LASTNAME, COMPANY) VALUES ('Jon', 'Doe', (SELECT ID FROM Company WHERE NAME = 'IT-soft'))
INSERT INTO Employee (FIRSTNAME, LASTNAME, COMPANY) VALUES ('Tim', 'Smith', (SELECT ID FROM Company WHERE NAME = 'IT-soft'))
INSERT INTO Employee (FIRSTNAME, LASTNAME, COMPANY) VALUES ('Kayne', 'Brad', (SELECT ID FROM Company WHERE NAME = 'I-Finance'))

INSERT INTO Project (DEADLINE, NAME) VALUES ('2018-06-18', 'ERP System')

INSERT INTO EMPLOYEES_PROJECTS (E_ID, P_ID) VALUES ((SELECT ID FROM Employee WHERE FIRSTNAME = 'Brad' AND LASTNAME = 'Hummy'), (SELECT ID FROM Project WHERE NAME = 'ERP System'))
INSERT INTO EMPLOYEES_PROJECTS (E_ID, P_ID) VALUES ((SELECT ID FROM Employee WHERE FIRSTNAME = 'Kayne' AND LASTNAME = 'Brad'), (SELECT ID FROM Project WHERE NAME = 'ERP System'))